import { arimo, domine } from "./font/font";
import "./globals.css";

export const metadata = {
  title: "Tech for Good",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${domine.variable} ${arimo.variable}`}>{children}</body>
    </html>
  );
}
