import Navbar from "@/components/navbar";
import "../../globals.css";
import { arimo, domine } from "@/font/font";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Build",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${domine.variable} ${arimo.variable}`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

//
